;
\o
\i ../DataBase/Create_HE_005.sql;
\c HE-006
\i ../Sequence/acquisition_configurations_id_seq.sql
\i ../Sequence/curent_sesion_id.sql
\i ../Sequence/data_id_seq1.sql
\i ../Sequence/devices_id.sql
\i ../Sequence/Errors_id.sql
\i ../Sequence/events_id.sql
\i ../Sequence/gas_types_id_seq.sql
\i ../Sequence/languages_id_seq.sql
\i ../Sequence/parameters_id_seq.sql
\i ../Sequence/priviliges_id_seq.sql
\i ../Sequence/program_configuration_id_seq.sql
\i ../Sequence/programs_id_seq.sql
\i ../Sequence/sesions_id_seq.sql
\i ../Sequence/stages_gas_id_seq.sql
\i ../Sequence/stages_power_supply_id_seq.sql
\i ../Sequence/stages_pump_id_seq.sql
\i ../Sequence/stages_purge_id_seq.sql
\i ../Sequence/stages_vent_id_seq.sql
\i ../Sequence/subprograms_id_seq.sql
\i ../Sequence/types_block_id_seq.sql
\i ../Sequence/users_id_seq.sql

\i ../Tables/languages_tab.sql
\i ../Tables/sesions_tab.sql
\i ../Tables/current_sesion_tab.sql
\i ../Tables/data_tab.sql
\i ../Tables/device_parameters_tab.sql
\i ../Tables/parameters_tab.sql
\i ../Tables/acquisition_configurations_tab.sql
\i ../Tables/devices_tab.sql
\i ../Tables/errors_txt_tab.sql
\i ../Tables/events_txt_tab.sql
\i ../Tables/gas_types_tab.sql
\i ../Tables/program_configuration_tab.sql
\i ../Tables/programs_tab.sql
\i ../Tables/stages_gas_tab.sql
\i ../Tables/stages_power_supply_tab.sql
\i ../Tables/stages_pump_tab.sql
\i ../Tables/stages_purge_tab.sql
\i ../Tables/stages_vent_tab.sql
\i ../Tables/subprograms_tab.sql
\i ../Tables/types_block_account_tab.sql
\i ../Tables/types_privilige_tab.sql
\i ../Tables/users_tab.sql
\i ../Tables/connections_program_subprograms_tab.sql

\i ../Functions/AddData.sql
\i ../Functions/AddGasType.sql
\i ../Functions/AddParameterConfig.sql
\i ../Functions/AddSubprogram.sql
\i ../Functions/GetData.sql
\i ../Functions/ModifyGasType.sql
\i ../Functions/ModifyParaConfig.sql
\i ../Functions/ModifyPrivilige.sql
\i ../Functions/ModifyProgram.sql
\i ../Functions/ModifySubprogram.sql
\i ../Functions/ModifySubprogram_Stage1.sql
\i ../Functions/ModifySubprogram_Stage2.sql
\i ../Functions/ModifyTypeBlockAccount.sql
\i ../Functions/ModifyUser.sql
\i ../Functions/NewPrivilige.sql
\i ../Functions/NewProgram.sql
\i ../Functions/NewTypeBlockAccount.sql
\i ../Functions/NewUser.sql
\i ../Functions/RegisterDevice.sql
\i ../Functions/RegisterParameter.sql
\i ../Functions/RemoveGasType.sql
\i ../Functions/RemovePrivilige.sql
\i ../Functions/RemoveProgram.sql
\i ../Functions/RemoveSubprogram.sql
\i ../Functions/RemoveTypeBlockAccount.sql
\i ../Functions/RemoveUser.sql
\i ../Functions/SaveParameter.sql
\i ../Functions/StartSesion.sql

\i ../View/ConfigProgramsAcq.sql
\i ../View/Devices.sql
\i ../View/Errors_Txt.sql
\i ../View/Events_Txt.sql
\i ../View/GasTypes.sql
\i ../View/ProgramParameters.sql
\i ../View/Programs.sql
\i ../View/Sesions.sql
\i ../View/Subprograms.sql
\i ../View/Users.sql

\i ../FillTables/Language.sql
\i ../FillTables/ErrorsTxt.sql
\i ../FillTables/EventsText.sql
\i ../FillTables/Types_Privilige.sql
\i ../FillTables/TypesBlockAccount.sql
\i ../FillTables/Users.sql